### PR TITLE
Update BFD build macros

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**
The bfd headers have been updated and the method signatures are different.

### CODE REVIEW

**Comment by hservatg** [comment]
In which binutils version did these changes appear? We're running this code on some machines and never seen that issue, but it could be that the machines use old binutils.

**Comment by h0lyalg0rithm** [comment]
@hservatg I am using a newer version of bfd utils.I tried the code on an old build of bfd and it works but it breaks on newer version.

**Comment by hservatg** [comment]
@h0lyalg0rithm -- but my reading of your patch I see that it does not cover both the new and the old routine signatures, does it? we would need a patch that supports both

**Comment by h0lyalg0rithm** [comment]
@hservatg I think it does, maybe I didnt understand well but I replicated the old method signature .So if we use the new version of bfd it should work and if you were using the older one it would just override the older macro.
Do you think there is another way to implement it?

**Comment by hservatg** [comment]
@h0lyalg0rithm  - Ok, it seems it compiles on an old system. I'm interested on giving it a full try but the system I use for testing purposes has an incompatible kernel right now. I'll accept the PR when I can confirm that the test works.

**Comment by hservatg** [comment]
Merged, thank you!

**Pull request merged**
